version: '3.8'

services:
  knx2mqtt:
    build:
      context: '.'
    image: 'knx2mqtt'
    restart: 'unless-stopped'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./knx2mqtt.yaml:/app/knx2mqtt.yaml
